### ISSUE TITLE
launcher pod is not OK when namespace set ResourceQuota

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/mpi-operator#53] opened 2018-09-30 02:37 UTC
1、 I set ResourceQuota of namespace cv. the yaml is as following
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: cv
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 30Gi
    requests.nvidia.com/gpu: 3
    limits.cpu: "3"
    limits.memory: 30Gi
    requests.nvidia.com/gpu: 3
```
2、I create mpijob as following. but only `mpijob-0-worker-0` and `mpijob-0-worker-1` pod is Running.
```
[root@ quota]# kubectl get pods -n cv
NAME                READY     STATUS    RESTARTS   AGE
mpijob-0-worker-0   1/1       Running   0          4m
mpijob-0-worker-1   1/1       Running   0          4m
```

```
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: mpijob-0
  namespace: cv
spec:
  backoffLimit: 0
  replicas: 2
  template:
    spec:
      containers:
        - image: uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5
        command:
          - mpirun
          - python
          - tensorflow_mnist.py
        imagePullPolicy: IfNotPresent
        name: mpijob-0
        resources:
        limits:
            cpu: "1"
            memory: 10Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "1"
            memory: 10Gi
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /examples/MNIST-data-0
          name: datavolume
        - mountPath: /examples/MNIST-data-1
          name: datavolume
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /opt/data/mnist
          type: DirectoryOrCreate
        name: datavolume
```

3、I delete ResourceQuota  of namespace cv that I create in step one. and all the pod is Running 
```
[root@quota]# kubectl get pods -n cv
NAME                      READY     STATUS    RESTARTS   AGE
mpijob-0-launcher-l97mr   1/1       Running   0          28s
mpijob-0-worker-0         1/1       Running   0          5m
mpijob-0-worker-1         1/1       Running   0          5m

```

I guess the reason is the launcher pod don't set  resouce Limits and Requests?
Could you mind to give the considerations you design to set  launcher pod QoS=BestEffort?

**Comment by rongou** [comment] 2018-10-01 16:11
Yeah right now we use the same pod spec for both the workers and the launcher, and mung the spec a little to make it work for the launcher. Since you already have a test case, do you mind sending a PR to fix it? Shouldn't be too involved. Probably around https://github.com/kubeflow/mpi-operator/blob/master/pkg/controllers/mpi_job_controller.go#L997

**Comment by tingweiwu** [comment] 2018-10-08 02:01
@rongou  do you mean to fix by setting the launcher pod's Limits and Requests as worker spec?
If we change it like this, it will occupy GPUS more than we need.  

Another solution is that when namespace set ResourceQuota, set the LimitRange at the same time.
[https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/](url)

**Comment by rongou** [comment] 2018-10-08 05:17
Oh I see the problem is the launcher doesn't have requests or limits set. Perhaps a short-term fix is to set them to something small, say 0.1 cpu and 500 mb memory? Longer term it seems we should separate out the pod specs for workers and the launcher. What do you think?

**Comment by rongou** [comment] 2018-10-09 16:04
Ok, I created a separate issue to track the api change.

Can your code be folded into the current controller?

**Comment by rongou** [comment] 2019-01-21 02:37
Marking this as a duplicate of #54

**Closed by rongou** 2019-01-21 02:37 UTC
Labels: duplicate
